name: CI JS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main", "mk/add-to-ci"]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    name: create-turbo
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.2.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        # corepack 0.10 has a race condition in it that can cause the inital
        # package manger installs to fail.
        # Once we update to a version of node that ships with corepack 0.12 or
        # higher we can remove the second install command.
        # Windows installs global packages to a directory that has lower priority than
        # the default node install so we also need to edit $PATH
        shell: bash
        run: |
          pnpm install;
          if [ "$RUNNER_OS" == "Windows" ]; then
            npm install --force --global corepack@latest
            npm config get prefix >> $GITHUB_PATH
          else
            npm install --global corepack@latest
          fi

      - name: Build & Test
        run: cd packages/create-turbo && pnpm test

